// Code generated by tools/genphones.js from phones/phones.json. DO NOT EDIT.

package phones

// Contract constants (docs/PHONE_FRAME.md).
const (
	DeckLogicalPx = 0
	RingOuterPx   = 4
	RingInnerPx   = 2
	RingPx        = 6
	TopHudPx      = 130
	DeckStackPx   = 600
	EncMaxW       = 1080
	EncMaxH       = 1920
	DefaultID     = "iphone-17"
)

// All is the selector-ordered table (popularity rank, then brand/model).
var All = []Phone{
	{ID: "iphone-17", Brand: "Apple", Model: "iPhone 17", Year: 2025, PhysW: 1206, PhysH: 2622, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 1, StreamW: 1206, StreamH: 2436},
	{ID: "iphone-17-pro-max", Brand: "Apple", Model: "iPhone 17 Pro Max", Year: 2025, PhysW: 1320, PhysH: 2868, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 2, StreamW: 1320, StreamH: 2682},
	{ID: "iphone-17-pro", Brand: "Apple", Model: "iPhone 17 Pro", Year: 2025, PhysW: 1206, PhysH: 2622, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 3, StreamW: 1206, StreamH: 2436},
	{ID: "galaxy-a07", Brand: "Samsung", Model: "Galaxy A07", Year: 2025, PhysW: 720, PhysH: 1600, DPRMilli: 2000, InsetTop: 24, InsetBottom: 16, Popularity: 4, StreamW: 720, StreamH: 1552},
	{ID: "galaxy-a17", Brand: "Samsung", Model: "Galaxy A17 (5G / 4G)", Year: 2025, PhysW: 1080, PhysH: 2340, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 5, StreamW: 1080, StreamH: 2277},
	{ID: "iphone-16", Brand: "Apple", Model: "iPhone 16", Year: 2024, PhysW: 1179, PhysH: 2556, DPRMilli: 3000, InsetTop: 59, InsetBottom: 34, Popularity: 6, StreamW: 1179, StreamH: 2379},
	{ID: "galaxy-s26-ultra", Brand: "Samsung", Model: "Galaxy S26 Ultra", Year: 2026, PhysW: 1440, PhysH: 3120, DPRMilli: 3500, InsetTop: 24, InsetBottom: 16, Popularity: 7, StreamW: 1440, StreamH: 3036},
	{ID: "galaxy-a56", Brand: "Samsung", Model: "Galaxy A56", Year: 2025, PhysW: 1080, PhysH: 2340, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 8, StreamW: 1080, StreamH: 2277},
	{ID: "galaxy-a36", Brand: "Samsung", Model: "Galaxy A36", Year: 2025, PhysW: 1080, PhysH: 2340, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 9, StreamW: 1080, StreamH: 2277},
	{ID: "galaxy-s26", Brand: "Samsung", Model: "Galaxy S26", Year: 2026, PhysW: 1080, PhysH: 2340, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 10, StreamW: 1080, StreamH: 2277},
	{ID: "iphone-16-pro-max", Brand: "Apple", Model: "iPhone 16 Pro Max", Year: 2024, PhysW: 1320, PhysH: 2868, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 11, StreamW: 1320, StreamH: 2682},
	{ID: "iphone-16-pro", Brand: "Apple", Model: "iPhone 16 Pro", Year: 2024, PhysW: 1206, PhysH: 2622, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 12, StreamW: 1206, StreamH: 2436},
	{ID: "iphone-15", Brand: "Apple", Model: "iPhone 15", Year: 2023, PhysW: 1179, PhysH: 2556, DPRMilli: 3000, InsetTop: 59, InsetBottom: 34, Popularity: 13, StreamW: 1179, StreamH: 2379},
	{ID: "iphone-15-pro-max", Brand: "Apple", Model: "iPhone 15 Pro Max", Year: 2023, PhysW: 1290, PhysH: 2796, DPRMilli: 3000, InsetTop: 59, InsetBottom: 34, Popularity: 14, StreamW: 1290, StreamH: 2619},
	{ID: "redmi-a5", Brand: "Xiaomi", Model: "Redmi A5", Year: 2025, PhysW: 720, PhysH: 1640, DPRMilli: 2000, InsetTop: 24, InsetBottom: 16, Popularity: 15, StreamW: 720, StreamH: 1592},
	{ID: "iphone-18-pro-max", Brand: "Apple", Model: "iPhone 18 Pro Max", Year: 2026, PhysW: 1320, PhysH: 2868, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 16, StreamW: 1320, StreamH: 2682},
	{ID: "iphone-18-pro", Brand: "Apple", Model: "iPhone 18 Pro", Year: 2026, PhysW: 1206, PhysH: 2622, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 17, StreamW: 1206, StreamH: 2436},
	{ID: "galaxy-s25-ultra", Brand: "Samsung", Model: "Galaxy S25 Ultra", Year: 2025, PhysW: 1440, PhysH: 3120, DPRMilli: 3500, InsetTop: 24, InsetBottom: 16, Popularity: 18, StreamW: 1440, StreamH: 3036},
	{ID: "iphone-14", Brand: "Apple", Model: "iPhone 14", Year: 2022, PhysW: 1170, PhysH: 2532, DPRMilli: 3000, InsetTop: 47, InsetBottom: 34, Popularity: 19, StreamW: 1170, StreamH: 2391},
	{ID: "pixel-10", Brand: "Google", Model: "Pixel 10", Year: 2025, PhysW: 1080, PhysH: 2424, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 20, StreamW: 1080, StreamH: 2361},
	{ID: "iphone-13", Brand: "Apple", Model: "iPhone 13", Year: 2021, PhysW: 1170, PhysH: 2532, DPRMilli: 3000, InsetTop: 47, InsetBottom: 34, Popularity: 0, StreamW: 1170, StreamH: 2391},
	{ID: "iphone-15-pro", Brand: "Apple", Model: "iPhone 15 Pro", Year: 2023, PhysW: 1179, PhysH: 2556, DPRMilli: 3000, InsetTop: 59, InsetBottom: 34, Popularity: 0, StreamW: 1179, StreamH: 2379},
	{ID: "iphone-16-plus", Brand: "Apple", Model: "iPhone 16 Plus", Year: 2024, PhysW: 1290, PhysH: 2796, DPRMilli: 3000, InsetTop: 59, InsetBottom: 34, Popularity: 0, StreamW: 1290, StreamH: 2619},
	{ID: "iphone-16e", Brand: "Apple", Model: "iPhone 16e", Year: 2025, PhysW: 1170, PhysH: 2532, DPRMilli: 3000, InsetTop: 47, InsetBottom: 34, Popularity: 0, StreamW: 1170, StreamH: 2391},
	{ID: "iphone-air", Brand: "Apple", Model: "iPhone Air", Year: 2025, PhysW: 1260, PhysH: 2736, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 0, StreamW: 1260, StreamH: 2550},
	{ID: "iphone-se-3", Brand: "Apple", Model: "iPhone SE (3rd gen)", Year: 2022, PhysW: 750, PhysH: 1334, DPRMilli: 2000, InsetTop: 20, InsetBottom: 0, Popularity: 0, StreamW: 750, StreamH: 1294},
	{ID: "generic-9-16", Brand: "Generic", Model: "Generic 9:16 stream (legacy band)", Year: 0, PhysW: 1080, PhysH: 2100, DPRMilli: 3000, InsetTop: 0, InsetBottom: 0, Popularity: 0, StreamW: 1080, StreamH: 1920},
	{ID: "pixel-10-pro", Brand: "Google", Model: "Pixel 10 Pro", Year: 2025, PhysW: 1280, PhysH: 2856, DPRMilli: 3000, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1280, StreamH: 2784},
	{ID: "pixel-9", Brand: "Google", Model: "Pixel 9", Year: 2024, PhysW: 1080, PhysH: 2424, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1080, StreamH: 2361},
	{ID: "oneplus-13", Brand: "OnePlus", Model: "OnePlus 13", Year: 2025, PhysW: 1440, PhysH: 3168, DPRMilli: 3500, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1440, StreamH: 3084},
	{ID: "galaxy-a16", Brand: "Samsung", Model: "Galaxy A16", Year: 2024, PhysW: 1080, PhysH: 2340, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1080, StreamH: 2277},
	{ID: "galaxy-s25", Brand: "Samsung", Model: "Galaxy S25", Year: 2025, PhysW: 1080, PhysH: 2340, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1080, StreamH: 2277},
	{ID: "galaxy-s26-plus", Brand: "Samsung", Model: "Galaxy S26+", Year: 2026, PhysW: 1440, PhysH: 3120, DPRMilli: 3500, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1440, StreamH: 3036},
	{ID: "redmi-note-14", Brand: "Xiaomi", Model: "Redmi Note 14", Year: 2025, PhysW: 1080, PhysH: 2400, DPRMilli: 2750, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1080, StreamH: 2334},
}

// ContractVectors mirrors phones/contract_vectors.json.
var ContractVectors = []Vector{
	{Phone: "iphone-17", ClientW: 3840, ClientH: 2160, X: 1388, Y: 6, W: 1063, H: 2148, EncW: 950, EncH: 1920},
	{Phone: "iphone-17", ClientW: 2560, ClientH: 1440, X: 926, Y: 6, W: 707, H: 1428, EncW: 706, EncH: 1428},
	{Phone: "iphone-17", ClientW: 1920, ClientH: 1080, X: 696, Y: 6, W: 529, H: 1068, EncW: 528, EncH: 1068},
	{Phone: "iphone-17", ClientW: 1280, ClientH: 720, X: 464, Y: 6, W: 351, H: 708, EncW: 350, EncH: 708},
	{Phone: "iphone-17", ClientW: 1366, ClientH: 768, X: 496, Y: 6, W: 374, H: 756, EncW: 374, EncH: 756},
	{Phone: "iphone-17", ClientW: 3440, ClientH: 1440, X: 1366, Y: 6, W: 707, H: 1428, EncW: 706, EncH: 1428},
	{Phone: "iphone-17", ClientW: 1920, ClientH: 1200, X: 666, Y: 6, W: 588, H: 1188, EncW: 588, EncH: 1188},
	{Phone: "iphone-17", ClientW: 1281, ClientH: 719, X: 466, Y: 6, W: 350, H: 707, EncW: 350, EncH: 706},
	{Phone: "iphone-17", ClientW: 1600, ClientH: 1000, X: 556, Y: 6, W: 489, H: 988, EncW: 488, EncH: 988},
	{Phone: "iphone-17", ClientW: 1080, ClientH: 1920, X: 68, Y: 6, W: 945, H: 1908, EncW: 944, EncH: 1908},
	{Phone: "galaxy-a07", ClientW: 3840, ClientH: 2160, X: 1422, Y: 6, W: 996, H: 2148, EncW: 890, EncH: 1920},
	{Phone: "galaxy-a07", ClientW: 2560, ClientH: 1440, X: 949, Y: 6, W: 662, H: 1428, EncW: 662, EncH: 1428},
	{Phone: "galaxy-a07", ClientW: 1920, ClientH: 1080, X: 712, Y: 6, W: 495, H: 1068, EncW: 494, EncH: 1068},
	{Phone: "galaxy-a07", ClientW: 1280, ClientH: 720, X: 476, Y: 6, W: 328, H: 708, EncW: 328, EncH: 708},
	{Phone: "galaxy-a07", ClientW: 1366, ClientH: 768, X: 508, Y: 6, W: 351, H: 756, EncW: 350, EncH: 756},
	{Phone: "galaxy-a07", ClientW: 3440, ClientH: 1440, X: 1389, Y: 6, W: 662, H: 1428, EncW: 662, EncH: 1428},
	{Phone: "galaxy-a07", ClientW: 1920, ClientH: 1200, X: 684, Y: 6, W: 551, H: 1188, EncW: 550, EncH: 1188},
	{Phone: "galaxy-a07", ClientW: 1281, ClientH: 719, X: 476, Y: 6, W: 328, H: 707, EncW: 328, EncH: 706},
	{Phone: "galaxy-a07", ClientW: 1600, ClientH: 1000, X: 571, Y: 6, W: 458, H: 988, EncW: 458, EncH: 988},
	{Phone: "galaxy-a07", ClientW: 1080, ClientH: 1920, X: 98, Y: 6, W: 885, H: 1908, EncW: 884, EncH: 1908},
	{Phone: "galaxy-s26-ultra", ClientW: 3840, ClientH: 2160, X: 1410, Y: 6, W: 1019, H: 2148, EncW: 910, EncH: 1920},
	{Phone: "galaxy-s26-ultra", ClientW: 2560, ClientH: 1440, X: 942, Y: 6, W: 677, H: 1428, EncW: 676, EncH: 1428},
	{Phone: "galaxy-s26-ultra", ClientW: 1920, ClientH: 1080, X: 706, Y: 6, W: 507, H: 1068, EncW: 506, EncH: 1068},
	{Phone: "galaxy-s26-ultra", ClientW: 1280, ClientH: 720, X: 472, Y: 6, W: 336, H: 708, EncW: 336, EncH: 708},
	{Phone: "galaxy-s26-ultra", ClientW: 1366, ClientH: 768, X: 504, Y: 6, W: 359, H: 756, EncW: 358, EncH: 756},
	{Phone: "galaxy-s26-ultra", ClientW: 3440, ClientH: 1440, X: 1382, Y: 6, W: 677, H: 1428, EncW: 676, EncH: 1428},
	{Phone: "galaxy-s26-ultra", ClientW: 1920, ClientH: 1200, X: 678, Y: 6, W: 563, H: 1188, EncW: 562, EncH: 1188},
	{Phone: "galaxy-s26-ultra", ClientW: 1281, ClientH: 719, X: 473, Y: 6, W: 335, H: 707, EncW: 334, EncH: 706},
	{Phone: "galaxy-s26-ultra", ClientW: 1600, ClientH: 1000, X: 566, Y: 6, W: 469, H: 988, EncW: 468, EncH: 988},
	{Phone: "galaxy-s26-ultra", ClientW: 1080, ClientH: 1920, X: 88, Y: 6, W: 905, H: 1908, EncW: 904, EncH: 1908},
	{Phone: "generic-9-16", ClientW: 3840, ClientH: 2160, X: 1316, Y: 6, W: 1208, H: 2148, EncW: 1080, EncH: 1920},
	{Phone: "generic-9-16", ClientW: 2560, ClientH: 1440, X: 878, Y: 6, W: 803, H: 1428, EncW: 802, EncH: 1428},
	{Phone: "generic-9-16", ClientW: 1920, ClientH: 1080, X: 660, Y: 6, W: 601, H: 1068, EncW: 600, EncH: 1068},
	{Phone: "generic-9-16", ClientW: 1280, ClientH: 720, X: 441, Y: 6, W: 398, H: 708, EncW: 398, EncH: 708},
	{Phone: "generic-9-16", ClientW: 1366, ClientH: 768, X: 470, Y: 6, W: 425, H: 756, EncW: 424, EncH: 756},
	{Phone: "generic-9-16", ClientW: 3440, ClientH: 1440, X: 1318, Y: 6, W: 803, H: 1428, EncW: 802, EncH: 1428},
	{Phone: "generic-9-16", ClientW: 1920, ClientH: 1200, X: 626, Y: 6, W: 668, H: 1188, EncW: 668, EncH: 1188},
	{Phone: "generic-9-16", ClientW: 1281, ClientH: 719, X: 442, Y: 6, W: 398, H: 707, EncW: 398, EncH: 706},
	{Phone: "generic-9-16", ClientW: 1600, ClientH: 1000, X: 522, Y: 6, W: 556, H: 988, EncW: 556, EncH: 988},
	{Phone: "generic-9-16", ClientW: 1080, ClientH: 1920, X: 6, Y: 10, W: 1068, H: 1899, EncW: 1068, EncH: 1898},
	{Phone: "iphone-se-3", ClientW: 3840, ClientH: 2160, X: 1298, Y: 6, W: 1245, H: 2148, EncW: 1080, EncH: 1862},
	{Phone: "iphone-se-3", ClientW: 2560, ClientH: 1440, X: 866, Y: 6, W: 828, H: 1428, EncW: 828, EncH: 1428},
	{Phone: "iphone-se-3", ClientW: 1920, ClientH: 1080, X: 650, Y: 6, W: 619, H: 1068, EncW: 618, EncH: 1068},
	{Phone: "iphone-se-3", ClientW: 1280, ClientH: 720, X: 435, Y: 6, W: 410, H: 708, EncW: 410, EncH: 708},
	{Phone: "iphone-se-3", ClientW: 1366, ClientH: 768, X: 464, Y: 6, W: 438, H: 756, EncW: 438, EncH: 756},
	{Phone: "iphone-se-3", ClientW: 3440, ClientH: 1440, X: 1306, Y: 6, W: 828, H: 1428, EncW: 828, EncH: 1428},
	{Phone: "iphone-se-3", ClientW: 1920, ClientH: 1200, X: 616, Y: 6, W: 689, H: 1188, EncW: 688, EncH: 1188},
	{Phone: "iphone-se-3", ClientW: 1281, ClientH: 719, X: 436, Y: 6, W: 410, H: 707, EncW: 410, EncH: 706},
	{Phone: "iphone-se-3", ClientW: 1600, ClientH: 1000, X: 514, Y: 6, W: 573, H: 988, EncW: 572, EncH: 988},
	{Phone: "iphone-se-3", ClientW: 1080, ClientH: 1920, X: 6, Y: 38, W: 1068, H: 1843, EncW: 1068, EncH: 1842},
}
