// Code generated by tools/genphones.js from phones/phones.json. DO NOT EDIT.

package phones

// Contract constants (docs/PHONE_FRAME.md).
const (
	DeckLogicalPx = 60
	RingOuterPx   = 4
	RingInnerPx   = 2
	RingPx        = 6
	EncMaxW       = 1080
	EncMaxH       = 1920
	DefaultID     = "iphone-17"
)

// All is the selector-ordered table (popularity rank, then brand/model).
var All = []Phone{
	{ID: "iphone-17", Brand: "Apple", Model: "iPhone 17", Year: 2025, PhysW: 1206, PhysH: 2622, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 1, StreamW: 1206, StreamH: 2154},
	{ID: "iphone-17-pro-max", Brand: "Apple", Model: "iPhone 17 Pro Max", Year: 2025, PhysW: 1320, PhysH: 2868, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 2, StreamW: 1320, StreamH: 2400},
	{ID: "iphone-17-pro", Brand: "Apple", Model: "iPhone 17 Pro", Year: 2025, PhysW: 1206, PhysH: 2622, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 3, StreamW: 1206, StreamH: 2154},
	{ID: "galaxy-a07", Brand: "Samsung", Model: "Galaxy A07", Year: 2025, PhysW: 720, PhysH: 1600, DPRMilli: 2000, InsetTop: 24, InsetBottom: 16, Popularity: 4, StreamW: 720, StreamH: 1400},
	{ID: "galaxy-a17", Brand: "Samsung", Model: "Galaxy A17 (5G / 4G)", Year: 2025, PhysW: 1080, PhysH: 2340, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 5, StreamW: 1080, StreamH: 2078},
	{ID: "iphone-16", Brand: "Apple", Model: "iPhone 16", Year: 2024, PhysW: 1179, PhysH: 2556, DPRMilli: 3000, InsetTop: 59, InsetBottom: 34, Popularity: 6, StreamW: 1179, StreamH: 2097},
	{ID: "galaxy-s26-ultra", Brand: "Samsung", Model: "Galaxy S26 Ultra", Year: 2026, PhysW: 1440, PhysH: 3120, DPRMilli: 3500, InsetTop: 24, InsetBottom: 16, Popularity: 7, StreamW: 1440, StreamH: 2770},
	{ID: "galaxy-a56", Brand: "Samsung", Model: "Galaxy A56", Year: 2025, PhysW: 1080, PhysH: 2340, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 8, StreamW: 1080, StreamH: 2078},
	{ID: "galaxy-a36", Brand: "Samsung", Model: "Galaxy A36", Year: 2025, PhysW: 1080, PhysH: 2340, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 9, StreamW: 1080, StreamH: 2078},
	{ID: "galaxy-s26", Brand: "Samsung", Model: "Galaxy S26", Year: 2026, PhysW: 1080, PhysH: 2340, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 10, StreamW: 1080, StreamH: 2078},
	{ID: "iphone-16-pro-max", Brand: "Apple", Model: "iPhone 16 Pro Max", Year: 2024, PhysW: 1320, PhysH: 2868, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 11, StreamW: 1320, StreamH: 2400},
	{ID: "iphone-16-pro", Brand: "Apple", Model: "iPhone 16 Pro", Year: 2024, PhysW: 1206, PhysH: 2622, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 12, StreamW: 1206, StreamH: 2154},
	{ID: "iphone-15", Brand: "Apple", Model: "iPhone 15", Year: 2023, PhysW: 1179, PhysH: 2556, DPRMilli: 3000, InsetTop: 59, InsetBottom: 34, Popularity: 13, StreamW: 1179, StreamH: 2097},
	{ID: "iphone-15-pro-max", Brand: "Apple", Model: "iPhone 15 Pro Max", Year: 2023, PhysW: 1290, PhysH: 2796, DPRMilli: 3000, InsetTop: 59, InsetBottom: 34, Popularity: 14, StreamW: 1290, StreamH: 2337},
	{ID: "redmi-a5", Brand: "Xiaomi", Model: "Redmi A5", Year: 2025, PhysW: 720, PhysH: 1640, DPRMilli: 2000, InsetTop: 24, InsetBottom: 16, Popularity: 15, StreamW: 720, StreamH: 1440},
	{ID: "iphone-18-pro-max", Brand: "Apple", Model: "iPhone 18 Pro Max", Year: 2026, PhysW: 1320, PhysH: 2868, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 16, StreamW: 1320, StreamH: 2400},
	{ID: "iphone-18-pro", Brand: "Apple", Model: "iPhone 18 Pro", Year: 2026, PhysW: 1206, PhysH: 2622, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 17, StreamW: 1206, StreamH: 2154},
	{ID: "galaxy-s25-ultra", Brand: "Samsung", Model: "Galaxy S25 Ultra", Year: 2025, PhysW: 1440, PhysH: 3120, DPRMilli: 3500, InsetTop: 24, InsetBottom: 16, Popularity: 18, StreamW: 1440, StreamH: 2770},
	{ID: "iphone-14", Brand: "Apple", Model: "iPhone 14", Year: 2022, PhysW: 1170, PhysH: 2532, DPRMilli: 3000, InsetTop: 47, InsetBottom: 34, Popularity: 19, StreamW: 1170, StreamH: 2109},
	{ID: "pixel-10", Brand: "Google", Model: "Pixel 10", Year: 2025, PhysW: 1080, PhysH: 2424, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 20, StreamW: 1080, StreamH: 2162},
	{ID: "iphone-13", Brand: "Apple", Model: "iPhone 13", Year: 2021, PhysW: 1170, PhysH: 2532, DPRMilli: 3000, InsetTop: 47, InsetBottom: 34, Popularity: 0, StreamW: 1170, StreamH: 2109},
	{ID: "iphone-15-pro", Brand: "Apple", Model: "iPhone 15 Pro", Year: 2023, PhysW: 1179, PhysH: 2556, DPRMilli: 3000, InsetTop: 59, InsetBottom: 34, Popularity: 0, StreamW: 1179, StreamH: 2097},
	{ID: "iphone-16-plus", Brand: "Apple", Model: "iPhone 16 Plus", Year: 2024, PhysW: 1290, PhysH: 2796, DPRMilli: 3000, InsetTop: 59, InsetBottom: 34, Popularity: 0, StreamW: 1290, StreamH: 2337},
	{ID: "iphone-16e", Brand: "Apple", Model: "iPhone 16e", Year: 2025, PhysW: 1170, PhysH: 2532, DPRMilli: 3000, InsetTop: 47, InsetBottom: 34, Popularity: 0, StreamW: 1170, StreamH: 2109},
	{ID: "iphone-air", Brand: "Apple", Model: "iPhone Air", Year: 2025, PhysW: 1260, PhysH: 2736, DPRMilli: 3000, InsetTop: 62, InsetBottom: 34, Popularity: 0, StreamW: 1260, StreamH: 2268},
	{ID: "iphone-se-3", Brand: "Apple", Model: "iPhone SE (3rd gen)", Year: 2022, PhysW: 750, PhysH: 1334, DPRMilli: 2000, InsetTop: 20, InsetBottom: 0, Popularity: 0, StreamW: 750, StreamH: 1174},
	{ID: "generic-9-16", Brand: "Generic", Model: "Generic 9:16 stream (legacy band)", Year: 0, PhysW: 1080, PhysH: 2100, DPRMilli: 3000, InsetTop: 0, InsetBottom: 0, Popularity: 0, StreamW: 1080, StreamH: 1920},
	{ID: "pixel-10-pro", Brand: "Google", Model: "Pixel 10 Pro", Year: 2025, PhysW: 1280, PhysH: 2856, DPRMilli: 3000, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1280, StreamH: 2556},
	{ID: "pixel-9", Brand: "Google", Model: "Pixel 9", Year: 2024, PhysW: 1080, PhysH: 2424, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1080, StreamH: 2162},
	{ID: "oneplus-13", Brand: "OnePlus", Model: "OnePlus 13", Year: 2025, PhysW: 1440, PhysH: 3168, DPRMilli: 3500, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1440, StreamH: 2818},
	{ID: "galaxy-a16", Brand: "Samsung", Model: "Galaxy A16", Year: 2024, PhysW: 1080, PhysH: 2340, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1080, StreamH: 2078},
	{ID: "galaxy-s25", Brand: "Samsung", Model: "Galaxy S25", Year: 2025, PhysW: 1080, PhysH: 2340, DPRMilli: 2625, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1080, StreamH: 2078},
	{ID: "galaxy-s26-plus", Brand: "Samsung", Model: "Galaxy S26+", Year: 2026, PhysW: 1440, PhysH: 3120, DPRMilli: 3500, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1440, StreamH: 2770},
	{ID: "redmi-note-14", Brand: "Xiaomi", Model: "Redmi Note 14", Year: 2025, PhysW: 1080, PhysH: 2400, DPRMilli: 2750, InsetTop: 24, InsetBottom: 16, Popularity: 0, StreamW: 1080, StreamH: 2125},
}

// ContractVectors mirrors phones/contract_vectors.json.
var ContractVectors = []Vector{
	{Phone: "iphone-17", ClientW: 3840, ClientH: 2160, X: 1318, Y: 6, W: 1203, H: 2148, EncW: 1074, EncH: 1920},
	{Phone: "iphone-17", ClientW: 2560, ClientH: 1440, X: 880, Y: 6, W: 800, H: 1428, EncW: 800, EncH: 1428},
	{Phone: "iphone-17", ClientW: 1920, ClientH: 1080, X: 661, Y: 6, W: 598, H: 1068, EncW: 598, EncH: 1068},
	{Phone: "iphone-17", ClientW: 1280, ClientH: 720, X: 442, Y: 6, W: 396, H: 708, EncW: 396, EncH: 708},
	{Phone: "iphone-17", ClientW: 1366, ClientH: 768, X: 472, Y: 6, W: 423, H: 756, EncW: 422, EncH: 756},
	{Phone: "iphone-17", ClientW: 3440, ClientH: 1440, X: 1320, Y: 6, W: 800, H: 1428, EncW: 800, EncH: 1428},
	{Phone: "iphone-17", ClientW: 1920, ClientH: 1200, X: 628, Y: 6, W: 665, H: 1188, EncW: 664, EncH: 1188},
	{Phone: "iphone-17", ClientW: 1281, ClientH: 719, X: 442, Y: 6, W: 396, H: 707, EncW: 396, EncH: 706},
	{Phone: "iphone-17", ClientW: 1600, ClientH: 1000, X: 524, Y: 6, W: 553, H: 988, EncW: 552, EncH: 988},
	{Phone: "iphone-17", ClientW: 1080, ClientH: 1920, X: 6, Y: 6, W: 1068, H: 1908, EncW: 1068, EncH: 1908},
	{Phone: "galaxy-a07", ClientW: 3840, ClientH: 2160, X: 1368, Y: 6, W: 1105, H: 2148, EncW: 988, EncH: 1920},
	{Phone: "galaxy-a07", ClientW: 2560, ClientH: 1440, X: 913, Y: 6, W: 734, H: 1428, EncW: 734, EncH: 1428},
	{Phone: "galaxy-a07", ClientW: 1920, ClientH: 1080, X: 686, Y: 6, W: 549, H: 1068, EncW: 548, EncH: 1068},
	{Phone: "galaxy-a07", ClientW: 1280, ClientH: 720, X: 458, Y: 6, W: 364, H: 708, EncW: 364, EncH: 708},
	{Phone: "galaxy-a07", ClientW: 1366, ClientH: 768, X: 488, Y: 6, W: 389, H: 756, EncW: 388, EncH: 756},
	{Phone: "galaxy-a07", ClientW: 3440, ClientH: 1440, X: 1353, Y: 6, W: 734, H: 1428, EncW: 734, EncH: 1428},
	{Phone: "galaxy-a07", ClientW: 1920, ClientH: 1200, X: 654, Y: 6, W: 611, H: 1188, EncW: 610, EncH: 1188},
	{Phone: "galaxy-a07", ClientW: 1281, ClientH: 719, X: 458, Y: 6, W: 364, H: 707, EncW: 364, EncH: 706},
	{Phone: "galaxy-a07", ClientW: 1600, ClientH: 1000, X: 546, Y: 6, W: 508, H: 988, EncW: 508, EncH: 988},
	{Phone: "galaxy-a07", ClientW: 1080, ClientH: 1920, X: 50, Y: 6, W: 981, H: 1908, EncW: 980, EncH: 1908},
	{Phone: "galaxy-s26-ultra", ClientW: 3840, ClientH: 2160, X: 1362, Y: 6, W: 1117, H: 2148, EncW: 998, EncH: 1920},
	{Phone: "galaxy-s26-ultra", ClientW: 2560, ClientH: 1440, X: 909, Y: 6, W: 742, H: 1428, EncW: 742, EncH: 1428},
	{Phone: "galaxy-s26-ultra", ClientW: 1920, ClientH: 1080, X: 682, Y: 6, W: 555, H: 1068, EncW: 554, EncH: 1068},
	{Phone: "galaxy-s26-ultra", ClientW: 1280, ClientH: 720, X: 456, Y: 6, W: 368, H: 708, EncW: 368, EncH: 708},
	{Phone: "galaxy-s26-ultra", ClientW: 1366, ClientH: 768, X: 486, Y: 6, W: 393, H: 756, EncW: 392, EncH: 756},
	{Phone: "galaxy-s26-ultra", ClientW: 3440, ClientH: 1440, X: 1349, Y: 6, W: 742, H: 1428, EncW: 742, EncH: 1428},
	{Phone: "galaxy-s26-ultra", ClientW: 1920, ClientH: 1200, X: 651, Y: 6, W: 618, H: 1188, EncW: 618, EncH: 1188},
	{Phone: "galaxy-s26-ultra", ClientW: 1281, ClientH: 719, X: 456, Y: 6, W: 368, H: 707, EncW: 368, EncH: 706},
	{Phone: "galaxy-s26-ultra", ClientW: 1600, ClientH: 1000, X: 543, Y: 6, W: 514, H: 988, EncW: 514, EncH: 988},
	{Phone: "galaxy-s26-ultra", ClientW: 1080, ClientH: 1920, X: 44, Y: 6, W: 992, H: 1908, EncW: 992, EncH: 1908},
	{Phone: "generic-9-16", ClientW: 3840, ClientH: 2160, X: 1316, Y: 6, W: 1208, H: 2148, EncW: 1080, EncH: 1920},
	{Phone: "generic-9-16", ClientW: 2560, ClientH: 1440, X: 878, Y: 6, W: 803, H: 1428, EncW: 802, EncH: 1428},
	{Phone: "generic-9-16", ClientW: 1920, ClientH: 1080, X: 660, Y: 6, W: 601, H: 1068, EncW: 600, EncH: 1068},
	{Phone: "generic-9-16", ClientW: 1280, ClientH: 720, X: 441, Y: 6, W: 398, H: 708, EncW: 398, EncH: 708},
	{Phone: "generic-9-16", ClientW: 1366, ClientH: 768, X: 470, Y: 6, W: 425, H: 756, EncW: 424, EncH: 756},
	{Phone: "generic-9-16", ClientW: 3440, ClientH: 1440, X: 1318, Y: 6, W: 803, H: 1428, EncW: 802, EncH: 1428},
	{Phone: "generic-9-16", ClientW: 1920, ClientH: 1200, X: 626, Y: 6, W: 668, H: 1188, EncW: 668, EncH: 1188},
	{Phone: "generic-9-16", ClientW: 1281, ClientH: 719, X: 442, Y: 6, W: 398, H: 707, EncW: 398, EncH: 706},
	{Phone: "generic-9-16", ClientW: 1600, ClientH: 1000, X: 522, Y: 6, W: 556, H: 988, EncW: 556, EncH: 988},
	{Phone: "generic-9-16", ClientW: 1080, ClientH: 1920, X: 6, Y: 10, W: 1068, H: 1899, EncW: 1068, EncH: 1898},
	{Phone: "iphone-se-3", ClientW: 3840, ClientH: 2160, X: 1234, Y: 6, W: 1372, H: 2148, EncW: 1080, EncH: 1690},
	{Phone: "iphone-se-3", ClientW: 2560, ClientH: 1440, X: 824, Y: 6, W: 912, H: 1428, EncW: 912, EncH: 1428},
	{Phone: "iphone-se-3", ClientW: 1920, ClientH: 1080, X: 619, Y: 6, W: 682, H: 1068, EncW: 682, EncH: 1068},
	{Phone: "iphone-se-3", ClientW: 1280, ClientH: 720, X: 414, Y: 6, W: 452, H: 708, EncW: 452, EncH: 708},
	{Phone: "iphone-se-3", ClientW: 1366, ClientH: 768, X: 442, Y: 6, W: 483, H: 756, EncW: 482, EncH: 756},
	{Phone: "iphone-se-3", ClientW: 3440, ClientH: 1440, X: 1264, Y: 6, W: 912, H: 1428, EncW: 912, EncH: 1428},
	{Phone: "iphone-se-3", ClientW: 1920, ClientH: 1200, X: 580, Y: 6, W: 759, H: 1188, EncW: 758, EncH: 1188},
	{Phone: "iphone-se-3", ClientW: 1281, ClientH: 719, X: 414, Y: 6, W: 452, H: 707, EncW: 452, EncH: 706},
	{Phone: "iphone-se-3", ClientW: 1600, ClientH: 1000, X: 484, Y: 6, W: 631, H: 988, EncW: 630, EncH: 988},
	{Phone: "iphone-se-3", ClientW: 1080, ClientH: 1920, X: 6, Y: 124, W: 1068, H: 1672, EncW: 1068, EncH: 1672},
}
